version: '3.4'

services:
  kruise.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}kruiseapi
    build:
      context: .
      dockerfile: Kruise.API/Dockerfile

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
     - 5433:5432
    volumes:
     - ./db-data:/var/lib/postgresql/data

  seq:
    container_name: seq
    image: datalust/seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
     - 5341:80
    volumes:
     - ./log-data:/data

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
     - 16686:16686
    volumes:
      - ./jaeger-ui:/etc/jaeger/