version: '3.4'

services:
  kruise.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}kruiseapi
    build:
      context: .
      dockerfile: Kruise.API/Dockerfile
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
     - 5433:5432
    volumes:
     - ./db-data:/var/lib/postgresql/data
